//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/msg")]
[System.Xml.Serialization.XmlRootAttribute("MAP-msg-listing", Namespace="http://tempuri.org/msg", IsNullable=false)]
public partial class MAPmsglisting {
    
    private msg[] msgField;
    
    private string versionField;
    
    public MAPmsglisting() {
        this.versionField = "1.0";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("msg")]
    public msg[] msg {
        get {
            return this.msgField;
        }
        set {
            this.msgField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/msg")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/msg", IsNullable=false)]
public partial class msg {
    
    private string handleField;
    
    private string subjectField;
    
    private string datetimeField;
    
    private string sender_nameField;
    
    private string sender_addressingField;
    
    private string replyto_addressingField;
    
    private string recipient_nameField;
    
    private string recipient_addressingField;
    
    private string typeField;
    
    private string sizeField;
    
    private msgText textField;
    
    private string reception_statusField;
    
    private string attachment_sizeField;
    
    private msgPriority priorityField;
    
    private msgRead readField;
    
    private msgSent sentField;
    
    private msgProtected protectedField;
    
    public msg() {
        this.textField = msgText.no;
        this.priorityField = msgPriority.no;
        this.readField = msgRead.no;
        this.sentField = msgSent.no;
        this.protectedField = msgProtected.no;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string handle {
        get {
            return this.handleField;
        }
        set {
            this.handleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string subject {
        get {
            return this.subjectField;
        }
        set {
            this.subjectField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string datetime {
        get {
            return this.datetimeField;
        }
        set {
            this.datetimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sender_name {
        get {
            return this.sender_nameField;
        }
        set {
            this.sender_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sender_addressing {
        get {
            return this.sender_addressingField;
        }
        set {
            this.sender_addressingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string replyto_addressing {
        get {
            return this.replyto_addressingField;
        }
        set {
            this.replyto_addressingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string recipient_name {
        get {
            return this.recipient_nameField;
        }
        set {
            this.recipient_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string recipient_addressing {
        get {
            return this.recipient_addressingField;
        }
        set {
            this.recipient_addressingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string size {
        get {
            return this.sizeField;
        }
        set {
            this.sizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(msgText.no)]
    public msgText text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string reception_status {
        get {
            return this.reception_statusField;
        }
        set {
            this.reception_statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string attachment_size {
        get {
            return this.attachment_sizeField;
        }
        set {
            this.attachment_sizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(msgPriority.no)]
    public msgPriority priority {
        get {
            return this.priorityField;
        }
        set {
            this.priorityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(msgRead.no)]
    public msgRead read {
        get {
            return this.readField;
        }
        set {
            this.readField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(msgSent.no)]
    public msgSent sent {
        get {
            return this.sentField;
        }
        set {
            this.sentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(msgProtected.no)]
    public msgProtected @protected {
        get {
            return this.protectedField;
        }
        set {
            this.protectedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/msg")]
public enum msgText {
    
    /// <remarks/>
    yes,
    
    /// <remarks/>
    no,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/msg")]
public enum msgPriority {
    
    /// <remarks/>
    yes,
    
    /// <remarks/>
    no,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/msg")]
public enum msgRead {
    
    /// <remarks/>
    yes,
    
    /// <remarks/>
    no,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/msg")]
public enum msgSent {
    
    /// <remarks/>
    yes,
    
    /// <remarks/>
    no,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/msg")]
public enum msgProtected {
    
    /// <remarks/>
    yes,
    
    /// <remarks/>
    no,
}
